# -*- coding: utf-8 -*-
"""Batch 66 Project 04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ue3Fa4WeAczAAHycrNqKydjAf7LOe_wf
"""

# you will work with random.choice(), if statements, and getting user input. This is a great project to help you build on the fundamentals like conditionals and functions.
# Project 4 Rock, paper, scissors Python Project
# My Name is: Abdul Majeed
# My Roll Number: PIAIC83322
# My Batch #: 66
# Class evening at SBSA on every saturday

import random
print("Welcome to Rock, Paper, Scissors game! \n")
user=input('Enter a choice \n (rock,paper,scissors):')
possible_actions=['rock','paper','scissors']
computer=random.choice(possible_actions)
print(f'\nYou chose {user}, computer chose {computer}')
if user==computer:
    print(f'Both players selected same action. It is a tie')
elif user=='rock':
    if computer=='scissors':
      print('Rock break the scissors! You win!')
elif user=='paper':
    if computer=='rock':
      print('Paper covers the rock. You win!')
elif user=='scissors':
    if computer=='paper':
      print('scissors cuts the paper. You win!')